// <auto-generated />
using System;
using AutoPcDemoWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPcDemoWebsite.Migrations
{
    [DbContext(typeof(TestingDataContext))]
    partial class TestingDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("AutoPcDemoWebsite.Models.TestData", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("CategoryOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryTwo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("TestDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
